# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orynwoggWi13qT7HDBTT5mB_PLzBwaAJ
"""

# ==============================
# TITANIC DATASET ANALYSIS
# Tech Stack: Python, Pandas, Matplotlib, Seaborn
# Platform: Google Colab
# ==============================

# 1. Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# 2. Load Dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print("\n========== DATA PREVIEW ==========\n")
display(df.head())

print("\n========== DATASET INFO ==========\n")
df.info()

print("\n========== SUMMARY STATISTICS ==========\n")
display(df.describe())

# 3. Missing Values Handling
print("\n========== MISSING VALUES (BEFORE) ==========\n")
print(df.isnull().sum())

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

print("\n========== MISSING VALUES (AFTER) ==========\n")
print(df.isnull().sum())

# ==============================
# VISUALIZATIONS
# ==============================

# Survival Count
plt.figure(figsize=(6,4))
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

print("\n" + "-"*60 + "\n")

# Survival by Gender
plt.figure(figsize=(6,4))
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.legend(title="Survived")
plt.tight_layout()
plt.show()

print("\n" + "-"*60 + "\n")

# Survival by Passenger Class
plt.figure(figsize=(6,4))
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

print("\n" + "-"*60 + "\n")

# Age Distribution
plt.figure(figsize=(7,4))
sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

print("\n" + "-"*60 + "\n")

# Fare vs Survival
plt.figure(figsize=(6,4))
sns.boxplot(x='Survived', y='Fare', data=df)
plt.title("Fare vs Survival")
plt.xlabel("Survived")
plt.ylabel("Fare")
plt.tight_layout()
plt.show()

print("\n" + "-"*60 + "\n")

# Correlation Heatmap
plt.figure(figsize=(8,6))
numeric_df = df.select_dtypes(include=['int64', 'float64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

# ==============================
# FINAL INSIGHTS
# ==============================

print("\n========== KEY INSIGHTS ==========\n")
print("1. Female passengers had a significantly higher survival rate.")
print("2. Passengers in higher classes showed better survival chances.")
print("3. Fare amount positively influenced survival.")
print("4. Younger passengers had slightly higher survival probability.")
print("5. Overall survival rate was approximately 38%.")